# -*- coding: utf-8 -*-
"""MinDistance.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18cuJy_i0YTs1_uv9wtLU_ubpfEvg4djO
"""

def distance(start,goal): # 両駅間の営業キロ(最小距離)
  #
  return 0.0; # km

def fare(distance): # 営業キロから運賃計算(IC料金)
  #
  return 140; # 円
