# -*- coding: utf-8 -*-
"""Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Sg7Qx7P8oo0_ficC0UZr0zPciiN2lfzd
"""


def get_whole_line_list():
  return []

def get_whole_station_list():
  return []